name: Daily ETL 

on:
  push:
    branches: [ main ]

  schedule:
    # Chạy 12h đêm 
    - cron: "0 17 * * *"
    # Chạy 6h sáng 
    - cron: "0 23 * * *"
    # Chạy 12h trưa 
    - cron: "0 5 * * *"
    # Chạy 6h chiều 
    - cron: "0 11 * * *"

  workflow_dispatch: # Cho phép chạy tay từ GitHub UI

jobs:
  daily-etl:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      # Đặt tên env đọc từ GitHub Secrets
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      # DB_URL: ${{ secrets.DB_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements/requirements.txt"

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          
      - name: Verify Chrome installation
        run: |
          echo "Chrome installed at: ${{ steps.setup-chrome.outputs.chrome-path }}"
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
      
      - name: Run extract (crawl)
        run: |
          python src/extract/crawl.py

      - name: Run load
        run: |
          python src/load/load_staging.py

      - name: Build quality dashboard
        run: python check_quality/dash_quality.py

      - name: Prepare dashboard
        run: |
          mkdir -p site
          cp dashboard_quality.html site/index.html

      - name: Upload dashboard artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy-dashboard:
    needs: daily-etl
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4     